steps:
  # Shallow fetch is done automatically in workspace dir. Might need to get more.
  # build the demo code
  - name: gradle:5.6.2-jdk8
    entrypoint: gradle
    args: ["test"]
  - name: gradle:5.6.2-jdk8
    entrypoint: gradle
    args: ["assemble"]
    dir: demo
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/demo", "--build-arg=JAR_FILE=build/libs/demo-0.0.1-SNAPSHOT.war", "."]
  images: ["gcr.io/$PROJECT_ID/demo"]
  # build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/demo:$COMMIT_SHA', '.']
  # push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/demo:$COMMIT_SHA']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'demo'
      - '--image'
      - 'gcr.io/$PROJECT_ID/demo:$COMMIT_SHA'
      - '--region'
      - 'us-west-3'
      - '--platform'
      - 'managed'
  images:
    - 'gcr.io/$PROJECT_ID/demo:$COMMIT_SHA'
    -